apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: ml
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://churn-model-demo-viraj/models/churn_model-55119d6d57ebfb38bda669f8e9544dfab9e05a2c.pkl
