name: MLOps Pipeline
 
on:
  push:
    branches:
      - mlops-cicd

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: churn-model-demo-viraj

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt
  
    - name: Generate dataset
      run: python generate_data.py

    - name: Train model
      run: python train.py

    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ env.AWS_REGION }}

    - name: Push model to S3
      run: |
        aws s3 cp models/churn_model.pkl s3://churn-model-demo-viraj/models/churn_model-${{ github.sha }}.pkl
        echo "Model pushed to s3 successfully"

    - name: Update inference.yaml with s3 model path
      run: |
        MODEL_URI="s3://churn-model-demo-viraj/models/churn_model-${{ github.sha }}.pkl"
        sed -i "s|storageUri: .*|storageUri: $MODEL_URI|g" k8s/inference.yaml

    - name: Commit updated inference.yaml
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add k8s/inference.yaml
        git commit -m "Update model S3 path" || echo "No changes"
        git push || echo "No changes to push"
